CREATE DATABASE demo OPTIONS (ANNOTATION 'Demo VDB');
USE DATABASE demo;

CREATE FOREIGN DATA WRAPPER "openapi";
CREATE SERVER cats TYPE 'NONE' FOREIGN DATA WRAPPER "openapi";
CREATE SCHEMA api SERVER cats;

SET SCHEMA api;
IMPORT FOREIGN SCHEMA public FROM SERVER cats INTO api;
